#!/usr/bin/env bash

entries=()
message=''

function update_entries() {
  SAVEIFS="$IFS" # Save current IFS
  IFS=$'\n'      # Change IFS to new line
  entries="$(
    rbw list --fields id,name,user,folder |
      sed --regexp-extended 's/([^\t]+?)\t([^\t]+?)\t([^\t]+?)\t([^\t]+?)/\4\/\2\t[\3]\t[id: \1]\\0icon\\x1ffolder\\x1finfo\\x1f\1/' |
      sed --regexp-extended 's|^/|(none)/|'
  )"
  entries=($entries)
  IFS="$SAVEIFS" # Restore IFS
}

function display_rofi() {
  for entry in "${entries[@]}"; do
    echo -e "$entry"
  done | rofi_config
}

function rofi_config() {
  _message="Alt+a - Sync | Alt+t - type username + password | Alt+p - copy password | Alt+u - copy username $message"
  message=''
  rofi \
    -i \
    -theme slate-slim \
    -no-custom \
    -location 1 \
    -theme-str '
      window {
        font: "Noto Sans 10";
        padding: 0;
        width: 100%;
      }

      listview {
        lines: 5;
      }

      inputbar { 
        children: [entry];
      }
    ' \
    -mesg "$_message" \
    -p 'Bitwarden' \
    -dmenu \
    -kb-custom-19 'Alt+a' \
    -kb-custom-11 'Alt+p' \
    -kb-custom-12 'Alt+u' \
    -kb-custom-13 'Alt+t' \
    $@
}

function do-type() {
  read -r data

  echo "$data" | xargs xdotool type --clearmodifiers
}

function do-copy() {
  read -r data

  echo "$data" | xclip -sel clip
}

function handle_rofi_type() {
  id="$1"
  field="$2"
  method="$3"

  sleep 0.1
  data=""
  case "$field" in
  "username")
    data="$(rbw list --fields id,user | grep "^$id" | cut -f2)"
    ;;

  "password")
    data="$(rbw get "$id")"
    ;;
  esac

  case "$method" in
  "type")
    echo "$data" | do-type
    ;;
  "copy")
    echo "$data" | do-copy
    ;;
  esac
}

rbw unlock || exit 2

update_entries

while true; do
  chosen="$(display_rofi)"
  exit_code="$?"
  chosen="$(echo "$chosen" | sed --regexp-extended "s|.*?\t\[id\: (.+?)\]$|\1|")"

  case "$exit_code" in
  0)
    handle_rofi_type "$chosen" "password" "type"
    ;;
  20)
    handle_rofi_type "$chosen" "password" "copy"
    exit
    ;;
  21)
    handle_rofi_type "$chosen" "username" "copy"
    exit
    ;;
  22)
    handle_rofi_type "$chosen" "username" "type"
    xdotool key --clearmodifiers Tab;
    handle_rofi_type "$chosen" "password" "type"
    exit
    ;;
  28)
    rbw sync
    update_entries
    message="| Synced"
    ;;
  *)
    exit 1
    ;;
  esac
done
