#!/usr/bin/env bash

CHOICES=(
	'lenny | ( ͡° ͜ʖ ͡°)'
	'shrug | ¯\_(ツ)_/¯'
	'moon | 🌚'
	'B | 🅱️'
	'communism | ☭'
	'sigma | Σ'
)

CHOICE="$(printf '%s\n' "${CHOICES[@]}" | rofi -dmenu -format i)"

if [ ! -z "$CHOICE" ]; then
	echo -n "${CHOICES[$CHOICE]}" |
		cut -d'|' -f2- |
		cut -c2- |
		tr '\n' '\0' |
		xargs -0 -I'{}' printf '%q' '{}' |
		xargs xdotool type
fi
