#!/usr/bin/node

const http = require('http');
const queryString = require('querystring');

async function request(url, options = {}) {
  return new Promise((resolve, reject) => {
    const finalOptions = Object.assign({ method: 'GET', body: '', asJSON: false }, options);

    http
      .request(url, finalOptions, (resp) => {
        let data = '';

        resp.setEncoding('utf8');

        resp.on('data', (chunk) => {
          data += chunk.toString();
        });

        resp.on('end', () => {
          const result = {
            body: data,
            headers: resp.headers,
          };

          if (finalOptions.asJSON) {
            result.body = JSON.parse(data);
          }

          resolve(result);
        });
      })
      .on('error', (err) => {
        console.log(err);
        reject(err);
      })
      .write(finalOptions.body);
  });
}

async function getCookie() {
  try {
    const {
      headers: {
        'set-cookie': rawCookie
      }
    } = await request('http://www.alfanum.co.rs/index.php/sr/demonstracija/demonstracija-tts');

    return rawCookie.pop().split(';').shift();
  } catch (e) {
    console.error(e);
    return null;
  }
}

async function main() {
  const cookie = await getCookie();
  const text = process.argv.slice(2).join(' ');

  const bodyData = {
    input_text: text,
    outlang: 'sr',
    speaker: 'AlfaNum Danica',
    rate: 0.9995,
    pitch: 0.875,
    port: 5040,
    enc: 1,
    address: 'tts4.alfanum.co.rs',
    server_id: 0,
  };

  const body =
    queryString
      .stringify(bodyData)
      .replace(/%20/g, '+');

  const payload = {
    method: 'POST',
    asJSON: true,
    headers: {
      'Referer': 'http://www.alfanum.co.rs/index.php/sr/demonstracija/demonstracija-tts',
      'Cookie': cookie,
      'Content-Length': Buffer.byteLength(body),
      'Content-Type': 'application/x-www-form-urlencoded',
      'Origin': 'http://www.alfanum.co.rs',
      'Host': 'www.alfanum.co.rs',
      'Accept': 'application/json',
    },
    body,
  };

  const { body: { file } } = await request('http://www.alfanum.co.rs/tts_req.php', payload);

  return `https://${bodyData.address}:5050/ttsnovi/${file}`;
}

main().then(console.log);
