#!/usr/bin/env python3
import argparse
import os

from python.downloaders import get_download_info


def main():
    parser = argparse.ArgumentParser(
        description="Download videos from gogo-stream.com",
        usage="%(prog)s [options] $GOGO_STREAM_URL",
    )

    parser.add_argument(
        "url",
        help="Name (from the site URL) of the series you want to download (eg. 'shingeki-no-kyojin')",
        type=str,
        nargs=1,
    )

    parser.add_argument(
        "-e", "--echo",
        help="If set returns the URL instead of downloading it",
        action=argparse.BooleanOptionalAction,
        default=False,
        dest="echo",
    )

    argv = parser.parse_args()

    gogostream_url = argv.url[0]
    should_just_echo = argv.echo

    download_info = get_download_info(url=gogostream_url)
    if download_info is None:
        exit(1)

    if should_just_echo:
        print(download_info.url, end="")
    else:
        os.system(
            f"yt-dlp --referer '{download_info.referer}' --downloader aria2c --downloader-args '-x 16' '{download_info.url}'")


if __name__ == "__main__":
    main()
