#!/usr/bin/env bash

FULLWIDTH_OUTPUT="$(
	echo "" |
		rofi \
			-dmenu \
			-theme-str '
				window {
					font: "Noto Sans 10";
					padding: 0;
				}

				listview {
					lines: 0;
				}
			' \
			-m \
			-4 \
			-p 'Fullwidth copy' |
		$HOME/.scripts/fullwidth-text
)"
if [ ! -z $FULLWIDTH_OUTPUT ]; then
	echo -n "$FULLWIDTH_OUTPUT" | xclip -sel clip
fi
