#!/usr/bin/env bash

FULLWIDTH_OUTPUT="$(
	echo "" |
		rofi \
			-dmenu \
			-theme-str '
				window {
					font: "Noto Sans 10";
					padding: 0;
				}

				listview {
					lines: 0;
				}
			' \
			-m \
			-4 \
			-p 'Fullwidth type' |
		$HOME/.scripts/fullwidth-text
)"
if [ ! -z $FULLWIDTH_OUTPUT ]; then
	OLD_CLIPBOARD_CONTENTS="$(xclip -o -selection clipboard)"
	CAN_RESTORE_CLIPBOARD=$?

	echo -n "$FULLWIDTH_OUTPUT" | xclip -selection clipboard && xdotool key --clearmodifiers 'Control_L+V'

	if [ $CAN_RESTORE_CLIPBOARD -eq 0 ]; then
		echo -n "$OLD_CLIPBOARD_CONTENTS" | xclip -selection clipboard
	fi
fi
