#!/usr/bin/env python
import sys
import os

wide_chars = {
    i: i + 0xFEE0
    for i
    in range(0x21, 0x7F)
}
wide_chars[0x20] = 0x3000


def widen_text(text: str) -> str:
    return text.translate(wide_chars)


if __name__ == "__main__":
    wide_text = widen_text(' '.join(sys.argv[1:]))

    if not os.isatty(0):
        wide_text += widen_text(sys.stdin.read())
        wide_text += widen_text(" ")

    sys.stdout.write(wide_text.strip())
