#!/usr/bin/env python3

import sys
import os.path
from typing import Union
from python.downloaders import handle__instagram_com

SESSION_ID_FILE = os.path.join(
    os.path.expanduser('~'),
    './.config/.secrets/instagram',
)


def get_input() -> Union[str, None]:
    urls = [url for url in sys.argv[1:]]
    if not sys.stdin.isatty():
        urls.extend(sys.stdin.readlines())

    return urls[0] if len(urls) > 0 else None


def main():
    res = handle__instagram_com(get_input())
    if res is None:
        return
    for url in res:
        print(url)


if __name__ == "__main__":
    main()
