#!/usr/bin/env bash

MEME_DIR="$HOME/MEMES"
FILE_IDENTIFIER="$(date -u '+%s%N' | base64 | rev | cut -c 3- | rev)"
OUTPUT_TEMPLATE="$MEME_DIR/$FILE_IDENTIFIER.%(id)s.%(ext)s"
if [ -z "$1" ]; then
  URL="$(echo "" | rofi -dmenu -lines 0 -m -4 -p '')"
else
  URL="$1"
fi
TMP_FILE="/tmp/$(basename $0)_"
TMP_FILE_LENGTH="${#TMP_FILE}"
TMP_FILE="$TMP_FILE$(printf '%q' "$URL" | sed -e 's|/|^|gi' | cut -c -$((255 - TMP_FILE_LENGTH))))"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"

if [[ -z "$URL" ]]; then
  exit 0
fi

(
  [[ -f "$HOME/.profile" ]] && source "$HOME/.profile"

  mkdir -p "$MEME_DIR"
  cd "$MEME_DIR"

  youtube-dl -o "$OUTPUT_TEMPLATE" --user-agent "$USER_AGENT" --exec 'touch {} && memfix {}' "$URL"

  FILE_EXISTS="$(find . -name "$FILE_IDENTIFIER.*")"

  if [[ $? -eq 0 && ! -z "$FILE_EXISTS" ]]; then
    echo "Downloaded"
  elif [[ "$URL" =~ https\:\/\/(www\.)?instagram\.com\/p\/.* ]]; then
    curl -sL --user-agent "$USER_AGENT" "$URL" |
      pup 'meta[property="og:image"] attr{content}' |
      sed -e 's/\&amp\;/\&/gi' |
      xargs youtube-dl -o "$OUTPUT_TEMPLATE" --exec 'touch "{}" && memfix "{}"'
  else
    notify-send \
      --urgency normal \
      --expire-time 5000 \
      --icon error \
      --app-name 'meme downloader' \
      'Download failed' \
      "The meme downloader couldn't download the provided page"

    exit 1
  fi

  notify-send \
    --urgency low \
    --expire-time 2000 \
    --icon success \
    --app-name 'meme downloader' \
    'Download finished' \
    "The MEME from $URL has finished downloading"
) &>"$TMP_FILE"
