#!/usr/bin/env bash

if [ -z "$1" ]; then
  URL="$(
    echo "" |
      rofi \
        -dmenu \
        -theme-str '
          window {
            font: "Noto Sans 10";
            padding: 0;
          }

          listview {
            lines: 0;
          }
        ' \
        -m \
        -4 \
			  -p 'mpv'
  )"
else
  URL="$1"
fi

if [ -z "$URL" ]; then
  exit 0
fi

mpv "$URL"
