#!/usr/bin/env bash

function fetch {
    curl -sL --fail "$1" 2>/dev/null || echo ""
}

URLS=(
    'https://ip.kset.org/'
    'https://checkip.amazonaws.com/'
    'http://icanhazip.com/'
    'https://api.ipify.org/?format=text'
)
IP=""
for URL in "${URLS[@]}"; do
    IP="$(fetch "$URL")"
    if [ -n "$IP" ]; then
        break
    fi
done

echo "$IP"
