#!/usr/bin/env bash

set -euo pipefail

if [ -n "${DEBUG:-}" ]; then
  set -x
fi

scrcpy_pid=""

function echo-billboard {
  local text="$1"
  local text_length="${#text}"
  # add extra 4 characters because of text additions
  text_length="$((text_length + 4))"

  local line="$(printf "%${text_length}s" "" | tr " " "=")"

  echo
  echo "$line"
  echo "= $text ="
  echo "$line"
  echo
}

function cleanup {
  echo-billboard "Phone webcam shutting down"

  if [ -n "$scrcpy_pid" ]; then
    echo "Stopping scrpy..."
    kill "$scrcpy_pid"
    wait -f "$scrcpy_pid" >/dev/null 2>&1 || true
    scrcpy_pid=""
    echo "scrpy stopped"
  fi

  echo "Removing v4l2loopback module..."
  doas modprobe --verbose --remove --wait 6000 v4l2loopback
  echo "v4l2loopback module removed"

  exit 0
}

# call cleanup when script exits or on SIGINT/SIGTERM/SIGHUP
trap cleanup EXIT

function main {
  # Wait for ADB device (phone) to connect
  adb wait-for-device

  # Unload current v4l2loopback module
  doas modprobe --verbose --remove --wait=2000 v4l2loopback

  # Insert v4l2loopback module with correct options
  doas modprobe --verbose v4l2loopback exclusive_caps=1 card_label="Phone Webcam"
  # doas modprobe --verbose v4l2loopback card_label="Phone Webcam"

  sleep 0.5

  # Get the first v4l2 device
  v4l2_device="$(v4l2-ctl --list-devices | grep /dev/video | awk '{print $1}' | head -n1)"

  if [ -z "$v4l2_device" ]; then
    echo "No v4l2 devices found!"
    exit 1
  fi

  echo "Using v4l2 device: $v4l2_device"

  # List available camera resolutions and fps:
  # scrcpy --list-camera-sizes

  # Stream phone camera to v4l2 device via scrcpy
  scrcpy \
    --video-source=camera \
    --camera-facing=back \
    --camera-ar=sensor \
    --max-size=1440 \
    --video-bit-rate=8M \
    --capture-orientation=@flip0 \
    --orientation=flip0 \
    --no-playback \
    --no-audio \
    --no-window \
    --v4l2-sink="$v4l2_device" \
    &

  scrcpy_pid="$!"

  echo-billboard "Phone webcam ready"

  wait "$scrcpy_pid"
}

main "$@"
