#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

clear_line() {
    printf "\r\033[2K"
}

print_status() {
    printf "\e[3;4m%s\e[0m\r" "$1"
}

print_status_report() {
    clear_line
    print_status "$1"
}

print_status_success() {
    printf "\e[30;42m %s \e[0m" "$1"
    shift
    if [ ! -z $1 ]; then
        printf " \e[4m%s\e[0m" "$*"
    fi
    printf "\n"
}

print_status_error() {
    printf "\e[1;101m %s \e[0m\n" "$1"
}

FILES=()
if [ $# -eq 0 ]; then
    print_status "Scanning..."
    while IFS= read -r -d $'\0'; do
        FILES+=("$REPLY")
    done < <(find . -name "*.mp4" -maxdepth 1 -type f -print0 2>/dev/null)
    print_status_report "Scanned"
else
    FILES=("$@")
fi

total="${#FILES[@]}"
processed=0
for filepath in "${FILES[@]}"; do
    print_status "Checking types... ($processed/${#FILES[@]})"

    location="$PWD"

    filename=$(basename -- "$filepath")
    filename="${filename%.*}"

    #HAS_AV1=$(mediainfo "$filepath" | grep -iE 'Format\s*:\s* av0?1')
    HAS_AV1=$(mediainfo --Inform="Video;%Format%" "$filepath" | grep -iE 'av0?1')
    if [[ ! -z "${HAS_AV1// /}" ]]; then
        printf "Transcoding \e[1;36;40m %s \e[0m... " "$filename"
        "$DIR/reencode-video-file" "$filepath" 2>/dev/null >/dev/null
        print_status_success "Done"
    fi
    ((processed += 1))
done
clear_line
