#!/usr/bin/env bash

TEMP_FILE="$(mktemp -d -t "tmp.XXXXXXXXXXXXXXXXXXXX")/$(basename "$1")"
OLD_TIME="$(stat -c '%y' "$1")"

ffmpeg -i "$1" -preset slow "$TEMP_FILE"
if command -v kioclient5 &>/dev/null; then
  kioclient5 move "$1" trash:/ 2>/dev/null
elif command -v trash-put &>/dev/null; then
  trash-put "$1"
fi
mv "$TEMP_FILE" "$1"
touch --date "$OLD_TIME" "$1"
