#!/usr/bin/env bash

SINKS=$(
    pactl list short sinks |
        cut -f1
)
SINKS=($SINKS)

CURRENT_SINK_NAME="$(
    pactl info |
        grep 'Default Sink: ' |
        cut -d ':' -f2 |
        tr -d '[:blank:]'
)"

CURRENT_SINK="$(
    pactl list short sinks |
        grep -P "\t$CURRENT_SINK_NAME\t" |
        cut -f1
)"

for i in "${!SINKS[@]}"; do
    if [[ "${SINKS[$i]}" = "${CURRENT_SINK}" ]]; then
        NEXT_SINK_SINKS_INDEX="$(((i + 1) % ${#SINKS[@]}))"
        break
    fi
done

NEW_SINK="${SINKS[$NEXT_SINK_SINKS_INDEX]}"

pactl set-default-sink "$NEW_SINK"

pactl list sink-inputs |
    grep -E '^S' |
    cut -d'#' -f2 |
    while read SINK_ID; do
        pactl \
            move-sink-input \
            "$SINK_ID" \
            "$NEW_SINK"
    done
