#!/usr/bin/env python3

import json
import sys
from urllib.parse import urlparse, parse_qs


def parse_url(raw_url: str) -> dict:
    url = raw_url.strip()

    if url.find('://') == -1 and not url.startswith('//'):
        parsed_url = urlparse('//' + url, 'http')
    else:
        parsed_url = urlparse(url)

    res = parsed_url._asdict()
    if res['query']:
        res['query'] = parse_qs(res['query'])

    return res


urls = [url for url in sys.argv[1:]]
if not sys.stdin.isatty():
    urls.extend(sys.stdin.readlines())
urls = [parse_url(raw_url=url) for url in urls]

print(json.dumps(urls))
