#!/usr/bin/env bash

# Generate a random file to dump the pallette to
palette_file="$(mktemp -t "mp4-to-gif.XXXXXXXXXXXXXXXXXXXX.png")"

input_file="$1"

# Extract filename without extension
filename="$(basename -- "$input_file")"
filename="${filename%.*}"

# Reduce FPS and scale down
filters="fps=30,scale=320:-2:flags=lanczos"

# Generate palette for the gif (vastly reduces size and somewhat improves quality)
ffmpeg \
  -v warning \
  -i "$input_file" \
  -vf "$filters,palettegen=stats_mode=diff" \
  -y "$palette_file"

# Generate the gif with the palette
ffmpeg \
  -v warning \
  -i "$input_file" \
  -i "$palette_file" \
  -lavfi "$filters [x]; [x][1:v] paletteuse=dither=floyd_steinberg" \
  -loop 0 \
  -y "$filename.gif"

# Clean up after yourself
rm "$palette_file"
